### ISSUE TITLE
程序结构

### ISSUE THREAD

**Issue by Fly2flies** [632team/EasyHousing#3]
你好，我最近才接触到SSM框架编程了，对您的项目有一点 不明白：就是为什么你src/main/java里 没有定理entity也就是各种java实体类的包？
还有就是您关于房子的数据是怎么得到的？是用爬虫爬然后存在数据库里吗？

**Comment by GooZy** [comment]
https://github.com/632team/EasyHousing/tree/master/src/com/easyhousing/model，这个？
数据我们当时直接随便写的，没精力搞爬虫 @STNobody

**Comment by Fly2flies** [comment]
嗯，我仔细看了一下，确实在model里定义了相关实体类。那您的地图显示方面是怎么实现的了，有用到百度或者高德的javasript的API吗？因为我看你保存很多重庆勒房子信息，但是没有经度维度什么的位置信息。我们想做一个能将一些房子的大地点在地图上显示的那种，能给点建议吗？
